<?php
/* account_data.php — 메디힘 계정관리 대장 (xlsx에서 추출, 정적) */
return [
  ['key'=>'site', 'title'=>'01. 매디힘 사이트 관리', 'cols'=>['NO','SITENAME','구분','WEB/APP','기타구분','URL','ID','PW','Port','주요기능','비고'], 'rows'=>[
    ['1','이뻐 상담앱','F/O','APP','운영','https://ippeo.io/','','','','',''],
    ['2','이뻐 상담앱','F/O','APP','개발(Dev)','https://dev.ippeo.io/','','','','',''],
    ['3','이뻐 상담앱_병원 WEB','B/O','WEB','개발(Dev)','https://dev.ippeo.io/seller','hyeri_01','a00000','','',''],
    ['4','이뻐 상담앱_관리자 WEB','B/O','WEB','개발(Dev)','https://dev.ippeo.io/master','manager','dreamer7100!@','','',''],
    ['','이뻐 상담앱_관리자 WEB','B/O','WEB','개발(Dev)','https://www.ippeo.io/master/auth/login','manager','dreamer7100!@','','',''],
    ['5','이뻐 병원신청','F/O','WEB','운영','https://ippeo.net','','','','',''],
    ['6','매디힘','F/O','WEB','운영','https://www.medihim.com/','','','','',''],
    ['7','Flex','인사','WEB','운영','https://flex.team/home','','','','',''],
    ['8','업무마켓','F/O','WEB','운영','https://buyr.workmarket9.com/login/userLogin','','','','',''],
    ['9','Notion','캐스팅앤','WEB','운영','https://www.notion.so/workmarket/IPPEO-home-1-28f3931a8fb580fc9737cdaf2c260e8b','','','','',''],
    ['10','Notion','프로젝트','WEB','운영','https://www.notion.so/2a1b4017fdb080e1b810c32488cd1172?v=2d8b4017fdb0801cb1d6000cc4f1516e&t=new','','','','','외주개발자(레빗)'],
    ['11','Figma','B/O','WEB','1차 개발 (Wireframe)','https://www.figma.com/design/Tct42GZOVUuS6v9mifw8aq/IPPEO-%EA%B5%AC%EC%B6%95-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EA%B3%B5%EC%9C%A0-?node-id=789-25707&p=f&t=y1Cp0WuljmOCAtvE-0','','1108.0','','','외주개발자(레빗)'],
    ['12','Figma','F/O','APP','1차 개발 (Wireframe)','https://www.figma.com/design/oXtxk8be9fdC58BVNK0pBk/-IPPEO--%EC%83%81%EB%8B%B4%EC%95%B1-%EC%A0%84%EB%8B%AC-%EC%8B%9C%EC%95%88?node-id=4587-3632&p=f&t=iImKocxYSzJ5WNwj-0','','','','',''],
    ['13','레드마인','일감 관리','System.Xml.XmlElement','','https://dev.ippeo.io/redmine/','ippeo','dreamer7100!@','','',''],
  ]],
  ['key'=>'vendor', 'title'=>'02. 거래업체', 'cols'=>['NO','구분','업체명','상품명','URL','ID','PW','담당자','직급/직책','부서','휴대폰','유선연락처','정기결제','세금계산서','비고'], 'rows'=>[
    ['1','이메일','하이웍스','웹호스팅','login.office.hiworks.com/ippeo.net','partners@ippeo.net','dreamer7100!@@','','','','','','','캐스팅엔',''],
    ['2','이미지 소스','프리픽','','https://kr.freepik.com/','hr@castingn.com','dreamer7100!@','','','','','','용 3601','캐스팅엔',''],
    ['3','웹빌더','아임웹','','https://imweb.me/','hr@castingn.com','Dreamer7100!@','','','','','','용 3601','캐스팅엔',''],
    ['4','도메인관리','가비아(캐스팅앤)','','https://www.gabia.com/','hrcastingn','dreamer7100!@','','','','','','','캐스팅엔',''],
    ['5','도메인관리','가비아(메디힘)','','https://www.gabia.com/','hrmedihim','dreamer7100!@','','','','','','','',''],
    ['6','디자인','피그마','','Figma','김이사님 개인 계정','','','','','','','용 3601','캐스팅엔',''],
    ['7','디자인','유토이미지','','https://www.utoimage.com/','medihim','dream20150325!@','','','','','','','캐스팅엔',''],
    ['8','도메인 관리','파일질라','','https://filezilla-project.org','호스트: ippeo.gabia.io 사용자명: ippeo 포트: 21','dreamer7100!@','','','','','','','','https://customer.gabia.com/manual/34/215/2504'],
    ['9','Google map','구글 콘솔','','https://console.cloud.google.com','administrator@castingn.com','sotkfkd@!0A','','','','','','','','2차 인증 박태석 CTO님'],
    ['10','','업무마켓 9','','https://buyr.workmarket9.com/','medihim_14','medihim_14+휴대폰번호 뒤 4자리+!','','','','','','','',''],
    ['11','','테스트 app 다운로드','','https://sp1public.s3.ap-northeast-2.amazonaws.com/ippeo/downloadPage.html','','','','','','','','','',''],
    ['12','병원 WEB','강남언니','','https://partner.gangnamunni.com/login?redirectUrl=%2Fdoctors','byulstar','byul1102','','','','','','','',''],
    ['13','화상솔루션','아고라','','https://console.agora.io/billing','hr@castingn.com','Ca69254932!@','박세빈','매니저','','010-5515-2111','','','',''],
    ['14','개발소스관리','GitLap','','https://github.com/projects','','','','','','','','','',''],
    ['15','결제,정산관리','엑심베이','','https://www.eximbay.com/index.do','IPPEO','dreamer7100!@','','','','','','','','MID : 2A53296875 APIKEY : live_2A5329687533C54FA22E'],
    ['16','Google','앱관리 대표메일','','https://mail.google.com/mail/u/0/#inbox','ippeodev@gmail.com','ippeodev2026!','법인폰 : 010-9457-4899','','','','','','',''],
    ['17','협업','Slack','','','ippeodev@gmail.com','ippeodev2026!','','','','','','','',''],
    ['18','AI','젠스파크','','https://www.genspark.ai/','workmarket9@castingn.com','a789456!@','','','','','','','',''],
    ['19','','카카오채널','','https://business.kakao.com/_RqQMX/dashboard','partners@ippeo.net','ippeo2026','','','','','','','',''],
    ['20','출력','킨코스','','https://www.kinkos.co.kr/','ippeo','dreamer7100!@','','','','','','','',''],
    ['21','','잡코리아','','https://www.jobkorea.co.kr','castingn','c69254932','','','','','','','',''],
    ['22','','LINE','','https://qr-official.line.me/gs/M_144lpwko_BW.png?oat_content=qr','partners@ippeo.net','2026dreamer!@','','','','','','','','베이직 아이디:@144lpwko'],
    ['23','','','','https://manager.line.biz/','','','','','','','','','','친추 링크: https://lin.ee/HbBSlbJ'],
    ['24','','','','https://www.lycbiz.com/jp/manual/','','','','','','','','','','백코드: 34RMY-NSZMQ HCNI5-GKBUZ KZQJE-2OBVJ 2QXOP-H6ZBE EGQH7-5SLAQ Z7HW4-KQFGG E6EDJ-MNLBE 665Y3-2ZMMR OPZAN-DRCIX TTCRO-V4JWA'],
    ['25','','채널톡','','','ippeodev@gmail.com','dreamer7100!@','','','','','','','',''],
  ]],
  ['key'=>'mobile', 'title'=>'03. 모바일 개발자계정', 'cols'=>['NO','구분','업체명','URL','등급구분','ID','PW','비고'], 'rows'=>[
    ['1','안드로이드 개발자 계정','구글','https://play.google.com/console/u/0/developers/4704544672990586467/app-list','','ippeodev@gmail.com','ippeodev2026!','Key store path : 키스토어 파일 경로 설정 Key store password : Key alias : 앱 정보 (보이지 않는 경우 Key store password 를 입력하고 오른쪽에 있는 폴더 아이콘을 클릭) 복구 이메일 partners@ippeo.net 복구 전화번호 0102106790'],
    ['2','IOS 개발자 계정','애플','https://appstoreconnect.apple.com/','기업계정','ippeodev@gmail.com','Medihim_2026!','복구 이메일 ippeodev@gmail.com 복구 전화번호 0102106790'],
    ['3','','','','엔터프라이즈 계정','','',''],
    ['4','','','','DUNS code','','',''],
    ['5','파이어베이스(푸시서비스)','','https://console.firebase.google.com/u/0/?utm_source=email&utm_medium=newsletter&utm_campaign=firebase-welcome','','','',''],
    ['6','원시그널(푸시서비스)','','https://onesignal.com/','','','','API - https://documentation.onesignal.com/reference/create-notification 샘플 application > controllers > Welocome.php파일에 push(), push_run() 메소드 확인하시면됩니다.'],
  ]],
  ['key'=>'test', 'title'=>'04. 테스트 계정', 'cols'=>['NO','기타구분','구분','SITENAME','WEB/APP','URL','ID','PW','Port','주요기능','비고'], 'rows'=>[
    ['2','개발(Dev)','사용자','이뻐 상담앱','APP','https://dev.ippeo.io/','jkpark@castingn.co.kr','moon020912!','','',''],
    ['3','개발(Dev)','관리자','이뻐 master','WEB','https://dev.ippeo.io/master/auth/login','manager','dreamer7100!@','','',''],
    ['4','개발(Dev)','관리자','병원관리자','WEB','https://dev.ippeo.io/seller/auth/login','seller01','a00000','','',''],
    ['','개발(Dev)','관리자','병원 상담실장','WEB','https://dev.ippeo.io/seller/auth/login','selseller01','qwer1245!','','',''],
    ['','개발(Dev)','관리자','원장님','WEB','https://dev.ippeo.io/seller/auth/login','docseller01','qwer1245!','','',''],
    ['','운영','사용자','이뻐 대표페이지','APP','https://ippeo.io/','','','','',''],
    ['','운영','관리자','이뻐 master','WEB','https://www.ippeo.io/master/auth/login','manager','dreamer7100!@','','',''],
    ['','운영','관리자','병원관리자','WEB','https://www.ippeo.io/seller/auth/login','ippeo2026','ippeo2026!','','',''],
    ['','운영','관리자','병원 상담실장','WEB','https://www.ippeo.io/seller/auth/login','ippeo0411_con','ippeo0411_con!','','',''],
    ['','운영','관리자','원장님','WEB','https://www.ippeo.io/seller/auth/login','ippeo0411_doc','ippeo0411_doc!','','',''],
    ['','운영','사용자','이뻐 상담앱','APP','(운영은 아래 \'APP 다운로드 URL\'에서 다운받으시고, 아래 계정으로 접속하시면 됩니다. 참고로, ios 다운로드 설정해주는게 좀 복잡해서, Android로 다운받으시길 권장듭니다.)','jkpark@castingn.co.kr','moon020912!','','',''],
    ['','운영/개발','사용자','APP 다운로드','','https://sp1public.s3.ap-northeast-2.amazonaws.com/ippeo/downloadPage.html','','','','',''],
  ]],
];
