<?php
/* schedule_data.php — 이뻐 Project 2차 구축 진척관리대장 (xlsx에서 정적 변환)
   자동 생성됨 — 수정 필요 시 server/_xlsx_to_php.py 재실행 또는 직접 수정. */

return [
  'meta' => [
  'title' => '이뻐 Project 2차 구축 진척관리대장',
  'version_line' => 'Version: 1.1 Last Updated: 2026.3.31',
  'total' => '32',
  'sheets_url' => '운영개발 SHEETS : https://docs.google.com/spreadsheets/d/1Mqy_dgW7GDlM9ajhCFWLsKEgOQGdtaK1jpPsnktWJhE/edit?gid=0#gid=0',
],
  'staff' => [
    ['프로젝트관리(PM)', '박진국'],
    ['기획(PL)', '박진국, 이홍근'],
    ['디자인(DE)', '한영은'],
    ['퍼블리싱(PU)', '강보성'],
    ['프론트엔드(APP)', '강보성'],
    ['백엔드(BE)', '김기문'],
  ],
  'stat_cols' => ['기획','디자인','퍼블리싱','프로그램'],
  'stats' => [
    ['진행예정', '15', '16', '22', '22'],
    ['진행중', '5', '2', '0', '6'],
    ['완료', '0', '1', '1', '3'],
    ['검수완료(최종)', '8', '0', '0', '0'],
    ['남은 개체수', '20', '19', '23', '31'],
    ['작업대상아님', '3', '11', '8', '0'],
    ['보류', '0', '0', '0', '0'],
    ['완료율', '0.25', '0', '0', '0'],
  ],
  'final_dates' => [
  '전체' => '2026-05-08',
  '디자인' => '2026-05-29',
  '퍼블리싱' => '2026-04-08',
  '개발' => '2026-05-29',
],
  'cols' => [
    ['key'=>'no', 'label'=>'번호', 'type'=>'int'],
    ['key'=>'phase', 'label'=>'차수', 'type'=>'str'],
    ['key'=>'priority', 'label'=>'우선순위', 'type'=>'str'],
    ['key'=>'platform', 'label'=>'APP/BO', 'type'=>'str'],
    ['key'=>'item', 'label'=>'항목', 'type'=>'str'],
    ['key'=>'requirement', 'label'=>'주요 요건정의', 'type'=>'str'],
    ['key'=>'history', 'label'=>'이슈/History', 'type'=>'str'],
    ['key'=>'progress_prev', 'label'=>'진행률(지난주)', 'type'=>'pct'],
    ['key'=>'progress_curr', 'label'=>'진행률(이번주)', 'type'=>'pct'],
    ['key'=>'start_date', 'label'=>'최초 시작일', 'type'=>'date'],
    ['key'=>'end_date', 'label'=>'최종 종료일', 'type'=>'date'],
    ['key'=>'final_status', 'label'=>'최종 상태', 'type'=>'str'],
    ['key'=>'workdays', 'label'=>'작업일수', 'type'=>'str'],
    ['key'=>'attach_plan', 'label'=>'기획서첨부', 'type'=>'str'],
    ['key'=>'attach_des', 'label'=>'디자인첨부', 'type'=>'str'],
    ['key'=>'attach_pub', 'label'=>'퍼블리싱첨부', 'type'=>'str'],
    ['key'=>'plan_status', 'label'=>'기획상태', 'type'=>'str'],
    ['key'=>'plan_owner', 'label'=>'기획담당', 'type'=>'str'],
    ['key'=>'plan_end', 'label'=>'기획종료일', 'type'=>'date'],
    ['key'=>'des_status', 'label'=>'디자인상태', 'type'=>'str'],
    ['key'=>'des_owner', 'label'=>'디자인담당', 'type'=>'str'],
    ['key'=>'des_end', 'label'=>'디자인종료일', 'type'=>'date'],
    ['key'=>'pub_status', 'label'=>'퍼블리싱상태', 'type'=>'str'],
    ['key'=>'pub_owner', 'label'=>'퍼블리싱담당', 'type'=>'str'],
    ['key'=>'pub_end', 'label'=>'퍼블리싱종료일', 'type'=>'date'],
    ['key'=>'dev_status', 'label'=>'개발상태', 'type'=>'str'],
    ['key'=>'dev_owner', 'label'=>'개발담당', 'type'=>'str'],
    ['key'=>'dev_end', 'label'=>'개발종료일', 'type'=>'date'],
    ['key'=>'dev_deploy', 'label'=>'개발서버반영일', 'type'=>'date'],
    ['key'=>'qa', 'label'=>'검수여부', 'type'=>'str'],
    ['key'=>'prod_deploy', 'label'=>'운영서버반영일', 'type'=>'date'],
  ],
  'items' => [
    [
  'no' => '1',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'APP/BO',
  'item' => 'AI 리포트',
  'requirement' => '',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-09',
  'end_date' => '2026-03-18',
  'final_status' => '기획진행중',
  'workdays' => '8',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행중',
  'plan_owner' => '이홍근',
  'plan_end' => '2026-04-03',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '2',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '앱 다운로드 관리',
  'requirement' => '- 고객이 이뻐를 다운로드한 내역을 리스트에서 확인할 수 있다. 
- 고객의 닉네임, 아이디, OS, 버전, 탈퇴여부등을 확인할 수 있다.',
  'history' => '',
  'progress_prev' => '100%',
  'progress_curr' => '',
  'start_date' => '2026-03-12',
  'end_date' => '2026-04-10',
  'final_status' => '운영서버반영완료',
  'workdays' => '22',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-10',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '완료',
  'dev_owner' => '김영훈/김진선/박우진',
  'dev_end' => '2026-03-27',
  'dev_deploy' => '2026-03-30',
  'qa' => '검수완료',
  'prod_deploy' => '2026-04-09',
],
    [
  'no' => '3',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '앱버전관리',
  'requirement' => 'OS별 앱 업그레이드 버전을 트레킹하여 리스트에 노출한다.',
  'history' => '',
  'progress_prev' => '100%',
  'progress_curr' => '',
  'start_date' => '2026-03-12',
  'end_date' => '2026-04-10',
  'final_status' => '운영서버반영완료',
  'workdays' => '22',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-10',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '완료',
  'dev_owner' => '김영훈/김진선/박우진',
  'dev_end' => '2026-03-27',
  'dev_deploy' => '2026-03-30',
  'qa' => '검수완료',
  'prod_deploy' => '2026-04-09',
],
    [
  'no' => '4',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'APP(WEB)',
  'item' => 'IPPEO 홈페이지',
  'requirement' => 'www.ippeo.io에 ippeo 랜딩페이지 적용
- 언어별 페이지 분리(국문, 일문)_변경기능 제공',
  'history' => '[박진국_2026.4.2]
한국어(웹페이지, 모바일페이지) 디자인완료

[박진국_2026.3.31]
2026.4.1에 디자인파일 첨부예정',
  'progress_prev' => '100%',
  'progress_curr' => '',
  'start_date' => '2026-03-02',
  'end_date' => '2026-04-08',
  'final_status' => '운영서버반영완료',
  'workdays' => '28',
  'attach_plan' => '',
  'attach_des' => '확인',
  'attach_pub' => '확인',
  'plan_status' => '작업대상아님',
  'plan_owner' => '',
  'plan_end' => '',
  'des_status' => '완료',
  'des_owner' => '김한나, 한영은',
  'des_end' => '2026-04-01',
  'pub_status' => '완료',
  'pub_owner' => '이효민',
  'pub_end' => '2026-04-08',
  'dev_status' => '완료',
  'dev_owner' => '박우진',
  'dev_end' => '2026-04-08',
  'dev_deploy' => '2026-04-09',
  'qa' => '검수완료',
  'prod_deploy' => '2026-04-09',
],
    [
  'no' => '5',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'APP/BO',
  'item' => '상담프로세스 개선',
  'requirement' => 'APP 
└ 상담리스트, 상담비 결제, 상담하기, 예약보증금 결제등 일련의 전 과정을 UI/UX 개선


BACK
└ 상담리스트, 상담상세, 상담하기, 예약확정등 일련의 전 과정의 UI/UX 개선
- 1차 상담자를 이뻐에서  병원 안내데스크로 변경하는 작업
- 2~3차는 순서에 관계없이 상담자/환자 모두 입장이 가능',
  'history' => '[박진국_2026.4.22]
- 기획서작성완료

[박진국_2026.4.21]
- 디자인 완료일자 : ~ 2026.4.30
- Description 작성중 : 기타업무로 인해 1일 지연예정 (~ 2026년 4월 22)

[박진국_2026.4.20]
- 1차 기획안 작성완료
- 디자인 및 일정 산정중
- 2026년 4월 21일까지 Description 작성목표

[박진국_2026.4.13]
2026년 4월 14일 최종기획서 작성완료

[박진국_2026.4.2]
- 기획서 수정완료 / Description 작성중 / 디자인팀 리뷰예정
- 채널톡 적용필요(계정등록(심사요청)중

[박진국_2026.4.1 / 2차]
김대진 이사님 리뷰완료 / 의견 받음(4/2 - 일부 기획수정완료예정)

[박진국_2026.4.1 / 1차]
1차 wireframe 완료 / 4.1 김대진이사님 리뷰 후 확정예정',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-19',
  'end_date' => '2026-05-29',
  'final_status' => '기획완료',
  'workdays' => '52',
  'attach_plan' => '확인',
  'attach_des' => '확인',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-30',
  'des_status' => '진행중',
  'des_owner' => '한영은',
  'des_end' => '2026-05-29',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '6',
  'phase' => '2차',
  'priority' => '',
  'platform' => '',
  'item' => 'UI/UX 2.0 개편 (홈 컨셉)',
  'requirement' => '홈 : 디지인 - 컨셉작업필요',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-04-06',
  'end_date' => '',
  'final_status' => '디자인진행중',
  'workdays' => '',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '',
  'plan_end' => '',
  'des_status' => '진행중',
  'des_owner' => '김한나, 한영은',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '8',
  'phase' => '1차 요건 + 2차 고도화',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '정산관리',
  'requirement' => '- 매출과 정산을 한눈에 확인 할 수 있는 페이지
- 이뻐는 상담비를 병원에, 병원은 확정금액을 정산처리해주도록 처리',
  'history' => '- 정산 기준은 확정일 지난 건수에 대해 익월에 청구
- 확정금액 수정시 정산 % 구간이 달라 질수 있으므로, 이에 대한 정책 확인이 필요

[박진국_2026.4.22]
- 예약보증금 + 잔금 결제 변경(병원 → 이뻐)으로 인한 기획서 수정
- 목표일정 : 2026년 5월 4일

[박진국_2026.4.1]
김대진 이사님 리뷰완료 / 의견 받음(4/2 - 일부 기획수정완료예정)

[박진국_2026.3.26]
- 부가세 계산방식 / 기준 확인필요
  └ 재무담당자 확인필요(리뷰예정)
- 상담비 요율에 따른 병원별 입금처리 API 문의 
  └ 엑심베이에서 병원별 정산처리 가능_엑심베이 담당자 확인완료
- 화상상담이 없는 이벤트 상품의 경우 정산에 빠져있고, 수수료 비율에도 빠져있고, 할건지 말건지.
  └ 화상상담이없는 이벤트 상품을 운영하지 않음. 이벤트등록 페이지에서 
      해당 기능 [상담이벤트 여부] 제거바랍니다._김대진 이사님 재가)
- 정산은 확정일자 기준으로 한다.',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-02-19',
  'end_date' => '2026-05-29',
  'final_status' => '기획완료',
  'workdays' => '72',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-25',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '7',
  'phase' => '1차 요건 + 2차 고도화',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '수수료 기능 2차 고도화',
  'requirement' => '- 이뻐, 에이전트의 수수료를 추가/수정/삭제가 가능하도록 기능개발
- 일괄 또는 각각 대상자에 따른 분리부과 가능',
  'history' => '- 상담비 경우 의사별로 지정할 수 있음.
- 상담비 : 결제 금액의 30%가 메디힘 / 70%병원
(PG 수수료는 메디힘에서 차감, 예약 수수료는 병원에서 차감)
- 구간에 들어가지 않는 케이스에 대해 디폴트 %정의 필요.
- 이상 ~ 미만으로 고정 검토 요청. 데이터 검증에 누락이 있을 가능성이 있음.

[박진국_2026.4.24]
- 변경불필요

[박진국_2026.4.22]
- 예약보증금 + 잔금 결제 변경(병원 → 이뻐)으로 인한 기획서 수정
- 목표일정 : 2026년 5월 4일

[박진국_2026.4.3]
부가세 추가 및 에이전트 \'사업자\', \'개인\'별 정산 항목 추가 기획중 (4/3 완료목표)

[박진국_2026.4.2 / 2차]
기획서 수정완료

[박진국_2026.4.2 / 1차]
개발팀(김영훈팀장)과 협의 후 일부기능 조정필요(기획수정중)
- 일괄적용 기능 삭제

[박진국_2026.4.1]
김대진 이사님 리뷰완료(확정)

[박진국_2026.3.26]
기획서 추가수정예정(오늘 완료 목표)_기획서 수정완료

[박진국_2026.3.25]
기획서 수정완료 (업데이트 완료)',
  'progress_prev' => '90%
(결제 연동 미적용)',
  'progress_curr' => '',
  'start_date' => '2026-03-10',
  'end_date' => '2026-05-29',
  'final_status' => '기획완료',
  'workdays' => '59',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-26',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '김영훈/김보경',
  'dev_end' => '2026-05-29',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '9',
  'phase' => '1차 요건 + 2차 고도화',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '결제관리(결제내역)',
  'requirement' => '- 기존 구현되어 있는 항목이 부족하여, 항목추가 및 UI/UX 개선
- 취소처리 및 실시간 데이터 노출 개선',
  'history' => '[박진국_2026.4.24]
- 기획서 변경완료 / 업데이트 완료

[박진국_2026.4.22]
- 예약보증금 + 잔금 결제 변경(병원 → 이뻐)으로 인한 기획서 수정
- 목표일정 : 2026년 5월 4일

[박진국_2026.4.1]
김대진 이사님 리뷰완료(확정)

[박진국_2026.3.26]
기획서 수정완료',
  'progress_prev' => '100%',
  'progress_curr' => '',
  'start_date' => '2026-02-19',
  'end_date' => '2026-04-24',
  'final_status' => '개발완료',
  'workdays' => '47',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-10',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '김영훈/김기령',
  'dev_end' => '2026-04-24',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '10',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '시술/수술 예약현황',
  'requirement' => '- 예약확정된 예약건에 대해 캘린더 형식으로 변경
- 주간/월간으로 노출
- 실시간으로 예약고객의 상태/정보를 확인 가능',
  'history' => '[박진국_2026.4.24]
- 기획서 변경불필요

[박진국_2026.4.22]
- 예약보증금 + 잔금 결제 변경(병원 → 이뻐)으로 인한 기획서 수정
- 목표일정 : 2026년 5월 4일

[박진국_2026.4.1]
김대진 이사님 리뷰완료(확정)

[박진국_2026.3.30]
기획서 수정완료',
  'progress_prev' => '진행률 : 99%
(관리자 링크 연동 미적용)',
  'progress_curr' => '',
  'start_date' => '2026-03-16',
  'end_date' => '2026-04-24',
  'final_status' => '개발진행중',
  'workdays' => '30',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-30',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '김영훈/김보경',
  'dev_end' => '2026-04-24',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '11',
  'phase' => '2차',
  'priority' => '1',
  'platform' => 'BO',
  'item' => '예약관리',
  'requirement' => '상담비 결제부터 잔금처리까지 일련의 과정을 한눈에 노출해주고, 완료처리등의 행위를 해줄 수 있도록 구현',
  'history' => '[박진국_2026.4.24]
- 기획서 변경완료 / 업데이트 완료

[박진국_2026.4.22]
- 예약보증금 + 잔금 결제 변경(병원 → 이뻐)으로 인한 기획서 수정
- 목표일정 : 2026년 5월 4일

[박진국_2026.4.1]
김대진 이사님 리뷰완료(확정)

[박진국_2026.3.26]
기획서 수정완료',
  'progress_prev' => '30%',
  'progress_curr' => '',
  'start_date' => '2026-03-16',
  'end_date' => '2026-05-29',
  'final_status' => '개발진행중',
  'workdays' => '55',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '검수완료',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-19',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '김영훈/김기령',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '12',
  'phase' => '',
  'priority' => '1',
  'platform' => 'IF',
  'item' => '인프라 재설정',
  'requirement' => 'AWS 분리 구성 작업',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-09',
  'end_date' => '2026-05-29',
  'final_status' => '개발진행중',
  'workdays' => '60',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '작업대상아님',
  'plan_owner' => '',
  'plan_end' => '',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '13',
  'phase' => '',
  'priority' => '1',
  'platform' => 'IF',
  'item' => 'DB 최신화',
  'requirement' => '기존 DB의 최신화 작업',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-09',
  'end_date' => '2026-05-29',
  'final_status' => '개발진행중',
  'workdays' => '60',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '작업대상아님',
  'plan_owner' => '',
  'plan_end' => '',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행중',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '14',
  'phase' => '',
  'priority' => '1',
  'platform' => 'APP',
  'item' => 'UI/UX 개선',
  'requirement' => '홈, 의사/병원리스트, 상담, 마이페이지, 후기등',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-09',
  'end_date' => '2026-05-29',
  'final_status' => '',
  'workdays' => '',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행중',
  'plan_owner' => '이홍근',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '15',
  'phase' => '',
  'priority' => '1',
  'platform' => 'BO',
  'item' => 'UI/UX 개선',
  'requirement' => '관리자페이지의 검색/리스트항목등을 전체적으로 표준화 및 고도화',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-03-09',
  'end_date' => '2026-05-29',
  'final_status' => '기획진행중',
  'workdays' => '52',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행중',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-20',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '16',
  'phase' => '',
  'priority' => '2',
  'platform' => 'BO',
  'item' => '에이전트 관리',
  'requirement' => '- 에이전트별 접속 계정 및 관련정보를 확인할 수 있는 관리자페이지
- 에이전트 정보/추천인/예약관리/정산관리',
  'history' => '[박진국_2026.3.26]
1차 기획서 (Description 작성전 / 현업부서 리뷰 및 의견 수집 후 최종안 작성완료예정)',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-04-07',
  'end_date' => '2026-05-29',
  'final_status' => '기획진행중',
  'workdays' => '',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행중',
  'plan_owner' => '박진국',
  'plan_end' => '2026-04-21',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '17',
  'phase' => '',
  'priority' => '2',
  'platform' => 'BO',
  'item' => '인플루언서 관리',
  'requirement' => '- 인플루언서별 접속 계정 및 관련정보를 확인할 수 있는 관리자페이지
- 인플루언서 정보/추천인/예약관리/정산관리',
  'history' => '[박진국_2026.3.26]
1차 기획서 (Description 작성전 / 현업부서 리뷰 및 의견 수집 후 최종안 작성완료예정)',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '2026-04-07',
  'end_date' => '2026-05-29',
  'final_status' => '기획진행중',
  'workdays' => '',
  'attach_plan' => '확인',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행중',
  'plan_owner' => '박진국',
  'plan_end' => '2026-04-21',
  'des_status' => '작업대상아님',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '작업대상아님',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '18',
  'phase' => '',
  'priority' => '2',
  'platform' => 'BO',
  'item' => '라인 알림',
  'requirement' => '',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-27',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '19',
  'phase' => '',
  'priority' => '2',
  'platform' => 'BO',
  'item' => '메일알림',
  'requirement' => '시스템 발송 이외에 마케팅용으로 발송이 가능한 시스템을 구현',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-27',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '20',
  'phase' => '',
  'priority' => '2',
  'platform' => 'BO',
  'item' => 'PUSH 고도화',
  'requirement' => '시스템 발송 이외에 마케팅용으로 발송이 가능한 시스템을 구현',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-27',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '21',
  'phase' => '',
  'priority' => '2',
  'platform' => 'APP/BO',
  'item' => '포인트관리',
  'requirement' => '- APP내에서 사용가능한 포인트 시스템을 구현한다. 
- 통합포인트 및 병원별 이용가능한 시스템을 구현한다. 
- 적립, 사용, 소멸등의 기능이 제공되며, 관리자가 증/차감하는 기능을 제공한다. 
- 마케팅용으로 활용도가 큼',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-04-10',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '22',
  'phase' => '',
  'priority' => '2',
  'platform' => 'APP/BO',
  'item' => '쿠폰관리',
  'requirement' => '- APP내에서 사용가능한 쿠폰 시스템을 구현한다. 
- 통합쿠폰 및 병원별 이용가능한 시스템을 구현한다. 
- 적립, 사용, 소멸등의 기능이 제공되며, 관리자가 증/차감하는 기능을 제공한다. 
- 마케팅용으로 활용도가 큼',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '이홍근',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '23',
  'phase' => '',
  'priority' => '3',
  'platform' => 'BO',
  'item' => '광고운영관리',
  'requirement' => '- 광고플랫폼 제공(APP에 노출될 광고를 병원에서 구좌별로 구매하며, CPC, CPA등 구매할 수 있도록 한다. 
- 광고주(병원)측에 관리기능을 제공하며, Report를 제공한다.',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '이홍근',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '24',
  'phase' => '',
  'priority' => '3',
  'platform' => 'BO',
  'item' => '이벤트 운영관리',
  'requirement' => '이벤트 APP내 이뻐/병원 이벤트/기획전을 할 수 있는 관리페이지를 구현한다.',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '이홍근',
  'plan_end' => '',
  'des_status' => '대상아님',
  'des_owner' => '',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '25',
  'phase' => '',
  'priority' => '3',
  'platform' => 'BO',
  'item' => '통계 리포트',
  'requirement' => '이뻐의 KPI를 확인할 수 잇는 통계프로그램을 구현한다.',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-05-08',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '26',
  'phase' => '',
  'priority' => '2',
  'platform' => 'APP',
  'item' => '오픈 이벤트',
  'requirement' => 'Grand open 시 이벤트를',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-31',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '27',
  'phase' => '',
  'priority' => '1',
  'platform' => 'APP',
  'item' => '통합검색기능 강화',
  'requirement' => '- 현재 DB검색으로 되어 있는 통합검색을 엘라서치등 자연어 검색엔진을 적용한다. 
- APP뿐아니라 관리자페이지에도 적용하면 로딩 속도가 확연히 개선된다.',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-31',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '28',
  'phase' => '',
  'priority' => '3',
  'platform' => 'APP/BO',
  'item' => '컨시어지',
  'requirement' => '여행, 항공, 숙박, 교통등의 서비스를 제공(외부업체와의 api등의 연동필요)',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국,이홍근',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '29',
  'phase' => '',
  'priority' => '3',
  'platform' => 'APP',
  'item' => '파트너 APP - 병원',
  'requirement' => '- 병원별 APP 구현
- 병원에서 실시간 예약현황, 정산관리, 화상상담을 APP내에서 진행이 가능하다.
- 이동성 편의
- Device : MOBILE, TABLET PC',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-04-24',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '30',
  'phase' => '2',
  'priority' => '3',
  'platform' => 'APP',
  'item' => '파트너 APP - 에이전트 / 인플루언서',
  'requirement' => '- 에이전트/인풀루언스별 APP 구현
- 병원에서 실시간 예약현황, 정산관리등을 APP내에서 확인이 가능하다.
- 인플루언스 APP의 경우 향 후 자신만의 컨텐츠등록, 관리, 회원유입등에 필수 APP이다.
- 이동성 편의
- Device : MOBILE, TABLET PC',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '박진국',
  'plan_end' => '2026-03-24',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '31',
  'phase' => '',
  'priority' => '3',
  'platform' => 'APP',
  'item' => '이뻐 관리자 APP',
  'requirement' => '이뻐 관리자 APP 구현
경영 또는 특정관리자별 필요한 정보만 확인할 수 있는 맞춤 APP 구현필요',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '이홍근',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
    [
  'no' => '32',
  'phase' => '',
  'priority' => '1',
  'platform' => '법률검토',
  'item' => '법률 검토 필요 사항 정리',
  'requirement' => '',
  'history' => '',
  'progress_prev' => '',
  'progress_curr' => '',
  'start_date' => '',
  'end_date' => '',
  'final_status' => '진행예정',
  'workdays' => '0',
  'attach_plan' => '',
  'attach_des' => '',
  'attach_pub' => '',
  'plan_status' => '진행예정',
  'plan_owner' => '',
  'plan_end' => '',
  'des_status' => '진행예정',
  'des_owner' => '선택',
  'des_end' => '',
  'pub_status' => '진행예정',
  'pub_owner' => '',
  'pub_end' => '',
  'dev_status' => '진행예정',
  'dev_owner' => '',
  'dev_end' => '',
  'dev_deploy' => '',
  'qa' => '선택',
  'prod_deploy' => '',
],
  ],
];
